### ISSUE TITLE
Project Brainstorming

### ISSUE THREAD

**Issue by wbp1702** [CSG-3613/alt-ctrl-team-4#1]
### Progress
We have not yet had a team meeting with all members present due to scheduling/contact issues. In the meetings that we have had, we did some brainstorming on project ideas which are listed below.

#### Game Ideas:
- Skydiving/Gliding.
- Canoe.

#### Controller Ideas:
- Puppet: Something similar to a Vudu doll that the player uses to control an in-game character.
- VHS: The player uses a VHS player to move the level through time.
- TV Remote: The player can switch between scenes using a remote.

### Next Steps
We are planning a full team meeting on Tuesday and hope to decide on a concept for the project soon.

**Comment by kimariana** [comment]
Weekly Update: April 8 - 12

## PROGRESS
We set up a discord server with everyone as a member. We watched videos about various alternate control ideas. We brainstormed concepts concerning the controls for a helicopter and a bike on 4/8 and 4/9. We ran into issues with planning for the implementation when trying to expand upon the rope aspect of a rescue helicopter. We met as a group in person with the Toy Design members on 4/11. We thought of new potential ideas but ended up refining the rescue helicopter idea for our project.

**Brainstorming Ideas:**
Progress on Tuesday:
- Rescue Helicopter- picking someone up to safety; hanging on a rope that has to be raised or lowered to avoid obstacles and dangers
- Biking- using an actual bike or front half of a bike to control the steering and movement

Progress on Thursday (Pictures by Jack):
![Brainstorming1](https://github.com/CSG-3613/alt-ctrl-team-4/assets/111906518/4b2f2342-1458-4528-8774-2eb72be0ae68)
![Brainstorming2](https://github.com/CSG-3613/alt-ctrl-team-4/assets/111906518/5385ba5b-c357-4351-af91-1d1d72ef81d2)
![Brainstorming3](https://github.com/CSG-3613/alt-ctrl-team-4/assets/111906518/28306356-c8df-478d-8687-03c5d23457d9)

Progress on Friday (Toy Design Team):
![Brainstorming4](https://github.com/CSG-3613/alt-ctrl-team-4/assets/111906518/b173e0f5-5f4a-4e73-95b4-e4af541edfd6)

## SLOWDOWNS
Schedule conflicts continued to persist initially. Not everyone was available to meet on Tuesday. We were only able to meet in person with mostly everyone on 4/11.

## COMPLETED
We finalized the rescue helicopter idea for our project. A 2 player game will be made where one player controls the vertical movement and speed of the helicopter while the other controls the vertical movement of the rescue rope.
